"""add vet column

Revision ID: 7dfe0857cbb5
Revises: ebaac0557d60
Create Date: 2024-05-09 00:31:03.111852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dfe0857cbb5'
down_revision = 'ebaac0557d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vet_specific_field', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('vet_specific_field')

    # ### end Alembic commands ###
